name: DeepHomes
main: me.wiefferink.areashop.AreaShop
version: "${project.version}${build.number}"
description: "Selling and renting WorldGuard regions to your players, highly configurable."
depend: [Vault, WorldGuard, WorldEdit]
softdepend: [Multiverse-Core, FastAsyncWorldEdit]
author: DevAustin
website: https://github.com/Whoops-Lambo/DeepHomes
commands:
  DeepHomes:
    description: 'For all commands use /dh help.'
    usage: 'DeepHomes has not started correctly, check the log file (or console) and correct any errors.'
    aliases: [dh]
awareness:
  - !@UTF8
api-version: 1.13
permissions:
  deephomes.*:
    description: Give access to all commands of DeepHomes
    children:
      deephomes.help: true
      deephomes.createrent: true
      deephomes.createbuy: true
      deephomes.destroyrent: true
      deephomes.destroybuy: true
      deephomes.rent: true
      deephomes.buy: true
      deephomes.buyresell: true
      deephomes.buynormal: true
      deephomes.unrent: true
      deephomes.info: true
      deephomes.reload: true
      deephomes.setrestore: true
      deephomes.setprice: true
      deephomes.setduration: true
      deephomes.teleport: true
      deephomes.teleportall: true
      deephomes.setteleportall: true
      deephomes.teleportsign: true
      deephomes.teleportsignall: true
      deephomes.tabcomplete: true
      deephomes.setteleportoutsideregion: true
      deephomes.find: true
      deephomes.groupadd: true
      deephomes.groupdel: true
      deephomes.grouplist: true
      deephomes.groupinfo: true
      deephomes.limitbypass: true
      deephomes.schematicevents: true
      deephomes.addsign: true
      deephomes.delsign: true
      deephomes.renttimebypass: true
      deephomes.me: true
      deephomes.resellall: true
      deephomes.stopresellall: true
      deephomes.addfriendall: true
      deephomes.delfriendall: true
      deephomes.notifyupdate: true
      deephomes.stack: true
      deephomes.setlandlord: true
      deephomes.linksigns: true
      deephomes.message: true
      deephomes.import: true
  deephomes.landlord.*:
    description: Give access to all landlord features
    children:
      deephomes.createrent.owner: true
      deephomes.createbuy.owner: true
      deephomes.setprice.landlord: true
      deephomes.setduration.landlord: true
      deephomes.destroyrent.landlord: true
      deephomes.destroybuy.landlord: true
  deephomes.help:
    description: Allows you to see the help pages
    default: true
  deephomes.rent:
    description: Allows you to rent a region
    default: true
  deephomes.buy:
    description: Allows you to buy a region
    default: true
  deephomes.buyresell:
    description: Allows you to buy a region that is in resell mode
    default: true
  deephomes.buynormal:
    description: Allows you to buy a region that is not in resell mode
    default: true
  deephomes.unrent:
    description: Allows you to unrent a specific region
    default: op
  deephomes.unrentown:
    description: Allows you to unrent your own region
    default: true
  deephomes.sell:
    description: Allows you to sell a specific region
    default: op
  deephomes.sellown:
    description: Allows you to sell your own region
    default: op
  deephomes.createrent:
    description: Allows you to add rent regions to DeepHomes
    default: op
  deephomes.createrent.member:
    description: Allows you to add rent regions to DeepHomes for which you are registered as member
    default: false
  deephomes.createrent.owner:
    description: Allows you to add rent regions to DeepHomes for which you are registered as owner
    default: false
  deephomes.createbuy:
    description: Allows you to add buy regions to DeepHomes
    default: op
  deephomes.createbuy.member:
    description: Allows you to add buy regions to DeepHomes for which you are registered as member
    default: false
  deephomes.createbuy.owner:
    description: Allows you to add buy regions to DeepHomes for which you are registered as owner
    default: false
  deephomes.destroyrent:
    description: Allows you remove rental regions from DeepHomes
    default: op
  deephomes.destroyrent.landlord:
    description: Allows you to remove rental regions from DeepHomes when you are the landlord
    default: false
  deephomes.destroybuy:
    description: Allows you to remove buy regions from DeepHomes
    default: op
  deephomes.destroybuy.landlord:
    description: Allows you to remove buy regions from DeepHomes when you are the landlord
    default: false
  deephomes.info:
    description: Allows you check the status of regions and players
    default: true
  deephomes.reload:
    description: Allows you to reload the config and update all region flags and signs
    default: op
  deephomes.setrestore:
    description: Allows you to change the restore settings
    default: op
  deephomes.setprice:
    description: Allows you to change the price
    default: op
  deephomes.setprice.landlord:
    description: Allows you to change the price of a region that you are landlord of
    default: false
  deephomes.setduration:
    description: Allows you to change the duration of a rent
    default: op
  deephomes.setduration.landlord:
    description: Allows you to change the duration of a region that you are landlord of
    default: false
  deephomes.teleport:
    description: Teleport to your region
    default: true
  deephomes.teleportall:
    description: Teleport to all regions
    default: op
  deephomes.teleportsign:
    description: Teleport to signs of regions you own
    default: true
  deephomes.teleportsignall:
    description: Teleport to signs of all regions
    default: op
  deephomes.teleportfriend:
    description: Teleport to regions where you are added as friend
    default: true
  deephomes.teleportfriendsign:
    description: Teleport to the sign of regions where you are added as friend
    default: true
  deephomes.teleportavailable:
    description: Teleport to regions which are available
    default: true
  deephomes.teleportavailablesign:
    description: Teleport to the sign of regions which are available
    default: true
  deephomes.setteleport:
    description: Set the teleport spot for your region
    default: true
  deephomes.setteleportall:
    description: Set the teleport for other regions
    default: op
  deephomes.setteleportoutsideregion:
    description: Set the teleport location outside the WorldGuard region
    default: op
  deephomes.tabcomplete:
    description: Allows you to tabcomplete all commands (also where you dont have permission)
    default: true
  deephomes.find:
    description: Allows you to teleport to a free region (/dh find)
    default: true
  deephomes.groupadd:
    description: Allows you to add regions to groups
    default: op
  deephomes.groupdel:
    description: Allows you to delete regions from groups
    default: op
  deephomes.grouplist:
    description: Allows you to list all the groups currently created
    default: op
  deephomes.groupinfo:
    description: Allows you to display information about a group (all members)
    default: op
  deephomes.rentextendbypass:
    description: Bypass the extend limit on rents
    default: op
  deephomes.limits.default:
    description: Assign limits as set in the 'default' group in the 'limitGroups' section of the config
    default: true
  deephomes.limitbypass:
    description: Bypass the limits for renting/buying regions (how many you can have at the same time)
    default: op
  deephomes.schematicevents:
    description: Allows you to trigger schematic events for regions
    default: op
  deephomes.addsign:
    description: Allows you to add signs to existing regions
    default: op
  deephomes.delsign:
    description: Allows you to delete signs from existing regions
    default: op
  deephomes.renttimebypass:
    description: Bypass the maximum rent time you can have in advance
    default: op
  deephomes.me:
    description: Allows you to get information about your regions
    default: true
  deephomes.setownerrent:
    description: Allows you to set the owner of rent regions
    default: op
  deephomes.setownerbuy:
    description: Allows you to set the owner of buy regions
    default: op
  deephomes.resell:
    description: Allows you to set your region to sell mode for selling to other players
    default: true
  deephomes.resellall:
    description: Allows you to set any region into selling mode
    default: op
  deephomes.stopresell:
    description: Allows you to set your region into normal mode if it is in sell mode
    default: true
  deephomes.stopresellall:
    description: Allows you to set any region into normal mode if it is in sell mode
    default: op
  deephomes.addfriend:
    description: Allows you to add friends to your regions
    default: true
  deephomes.addfriendall:
    description: Allows you to add friends to all regions
    default: op
  deephomes.delfriend:
    description: Allows you to delete friends from your regions
    default: true
  deephomes.delfriendall:
    description: Allows you to delete friends from all regions
    default: op
  deephomes.notifyupdate:
    description: Will notify this player when an update is available
    default: op
  deephomes.linksigns:
    description: Allows you to enter sign linking mode
    default: op
  deephomes.stack:
    description: Allows you to create regions and add them to AreaShop like the WorldEdit //stack command
    default: op
  deephomes.setlandlord:
    description: Allows you to set the landlord of a region, the landlord receives all revenue
    default: op
  deephomes.message:
    description: Allows you to send DeepHomes messages to players
    default: op
  deephomes.import:
    description: Allows importing regions from other plugins
    default: op
